version: '3'
services:
  unleash-server:
    image: unleashorg/unleash-server
    container_name: unleash
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://postgres:unleash4All@db:5432/unleash
      HTTP_PORT: 4242
      DATABASE_SSL: 'false'
    depends_on:
      - db
    networks:
      - unleash
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unleash4All
      POSTGRES_DB: unleash
    networks:
      - unleash

networks:
  unleash:
    driver: bridge